/**
 * Framework adapter scaffolders — emits a minimal `bootstrap` + rspack config
 * for Vue, Svelte, or Solid. The MOXJS runtime is already framework-neutral
 * (router + remote loader + telemetry), so these scaffolders only need to
 * generate the host's mount glue and the per-framework Rspack loader.
 *
 * Pure file emission: every template is a string template; no third-party
 * dependencies are imported at CLI-resolution time. Tests assert on emitted
 * filenames and key content fragments.
 */

import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

export type Framework = 'vue' | 'svelte' | 'solid';

export interface FrameworkAdapterTemplate {
  files: Record<string, string>;
  /** Rspack loader package names to add to devDependencies. */
  devDeps: Record<string, string>;
  /** Runtime deps the user needs to install. */
  deps: Record<string, string>;
  /** Short, single-line summary for stdout. */
  summary: string;
}

const VUE_BOOTSTRAP = `import { createApp, h } from 'vue';
import { getRouter, usePathname } from '@moxjs/runtime';

getRouter();

const App = {
  setup() {
    const path = usePathname();
    return () => h('div', [
      h('header', 'MOXJS · Vue host'),
      h('main', \`route: \${path}\`),
    ]);
  },
};

createApp(App).mount('#root');
`;

const SVELTE_BOOTSTRAP = `import App from './App.svelte';
import { getRouter } from '@moxjs/runtime';

getRouter();
new App({ target: document.getElementById('root')! });
`;

const SVELTE_APP = `<script lang="ts">
  import { onMount } from 'svelte';
  import { getRouter } from '@moxjs/runtime';

  let pathname = '/';
  onMount(() => {
    const off = getRouter().subscribe((p) => (pathname = p));
    return off;
  });
</script>

<header>MOXJS · Svelte host</header>
<main>route: {pathname}</main>
`;

const SOLID_BOOTSTRAP = `import { render } from 'solid-js/web';
import { createSignal, onCleanup } from 'solid-js';
import { getRouter } from '@moxjs/runtime';

function App() {
  const [pathname, setPathname] = createSignal('/');
  const off = getRouter().subscribe(setPathname);
  onCleanup(off);
  return (
    <div>
      <header>MOXJS · Solid host</header>
      <main>route: {pathname()}</main>
    </div>
  );
}

render(() => <App />, document.getElementById('root')!);
`;

function rspackConfig(framework: Framework, name: string, port: number): string {
  // Pick the framework-specific loader chain. We keep this dependency-free —
  // the loader packages are listed in `devDeps` for the user to install.
  let loader: string;
  switch (framework) {
    case 'vue':
      loader = `      { test: /\\.vue$/, use: ['vue-loader'] },\n` +
               `      { test: /\\.ts$/, use: ['ts-loader'] },`;
      break;
    case 'svelte':
      loader = `      { test: /\\.svelte$/, use: ['svelte-loader'] },\n` +
               `      { test: /\\.ts$/, use: ['ts-loader'] },`;
      break;
    case 'solid':
      loader = `      { test: /\\.tsx$/, use: { loader: 'babel-loader', options: { presets: ['solid'] } } },`;
      break;
  }
  return `// rspack.config.mjs — generated by \`moxjs generate remote --framework ${framework}\`
export default {
  lazyCompilation: false,
  entry: { main: './src/bootstrap.${framework === 'svelte' ? 'ts' : framework === 'solid' ? 'tsx' : 'ts'}' },
  output: { publicPath: 'auto' },
  devServer: { port: ${port} },
  module: {
    rules: [
${loader}
    ],
  },
};
`;
}

function packageJson(framework: Framework, name: string): string {
  const dev = devDepsFor(framework);
  const deps = depsFor(framework);
  return JSON.stringify(
    {
      name: `@app/${name}`,
      private: true,
      type: 'module',
      scripts: { dev: 'rspack serve', build: 'rspack build' },
      dependencies: deps,
      devDependencies: dev,
    },
    null,
    2,
  ) + '\n';
}

function depsFor(framework: Framework): Record<string, string> {
  switch (framework) {
    case 'vue':
      return { vue: '^3.4.0', '@moxjs/runtime': 'workspace:*' };
    case 'svelte':
      return { svelte: '^4.2.0', '@moxjs/runtime': 'workspace:*' };
    case 'solid':
      return { 'solid-js': '^1.8.0', '@moxjs/runtime': 'workspace:*' };
  }
}

function devDepsFor(framework: Framework): Record<string, string> {
  switch (framework) {
    case 'vue':
      return { 'vue-loader': '^17.4.0', 'ts-loader': '^9.5.0', '@rspack/cli': '^1.0.0', '@rspack/core': '^1.0.0', typescript: '^5.7.0' };
    case 'svelte':
      return { 'svelte-loader': '^3.2.0', 'svelte-preprocess': '^5.1.0', 'ts-loader': '^9.5.0', '@rspack/cli': '^1.0.0', '@rspack/core': '^1.0.0', typescript: '^5.7.0' };
    case 'solid':
      return { 'babel-loader': '^9.1.0', 'babel-preset-solid': '^1.8.0', '@rspack/cli': '^1.0.0', '@rspack/core': '^1.0.0', typescript: '^5.7.0' };
  }
}

export function buildAdapterTemplate(framework: Framework, name: string, port: number): FrameworkAdapterTemplate {
  const files: Record<string, string> = {
    'package.json': packageJson(framework, name),
    'rspack.config.mjs': rspackConfig(framework, name, port),
    'moxjs.app.json': JSON.stringify({ name, type: 'remote', port, framework }, null, 2) + '\n',
  };
  switch (framework) {
    case 'vue':
      files['src/bootstrap.ts'] = VUE_BOOTSTRAP;
      break;
    case 'svelte':
      files['src/bootstrap.ts'] = SVELTE_BOOTSTRAP;
      files['src/App.svelte'] = SVELTE_APP;
      break;
    case 'solid':
      files['src/bootstrap.tsx'] = SOLID_BOOTSTRAP;
      break;
  }
  return {
    files,
    deps: depsFor(framework),
    devDeps: devDepsFor(framework),
    summary: `${framework} remote "${name}" on port ${port}`,
  };
}

export interface ScaffoldFrameworkOptions {
  cwd: string;
  framework: Framework;
  name: string;
  port?: number;
  force?: boolean;
}

export async function scaffoldFrameworkRemote(opts: ScaffoldFrameworkOptions): Promise<{
  appDir: string;
  written: string[];
  skipped: string[];
  summary: string;
}> {
  const cwd = path.resolve(opts.cwd);
  const appDir = path.join(cwd, 'apps', opts.name);
  await fs.ensureDir(appDir);
  const port = opts.port ?? 3100;
  const template = buildAdapterTemplate(opts.framework, opts.name, port);
  const written: string[] = [];
  const skipped: string[] = [];
  for (const [rel, contents] of Object.entries(template.files)) {
    const dest = path.join(appDir, rel);
    if ((await fs.pathExists(dest)) && !opts.force) {
      skipped.push(rel);
      continue;
    }
    await fs.ensureDir(path.dirname(dest));
    await fs.writeFile(dest, contents, 'utf8');
    written.push(rel);
  }
  return { appDir, written, skipped, summary: template.summary };
}

export const adapterCommand = new Command('adapter')
  .description('Scaffolders for non-React frameworks (Vue / Svelte / Solid).')
  .command('add <framework>')
  .description('Create a new remote built with the chosen framework.')
  .requiredOption('--name <name>', 'App name (becomes apps/<name>/)')
  .option('--port <n>', 'Dev-server port', (v) => Number(v))
  .option('--cwd <dir>', 'Workspace root', process.cwd())
  .option('--force', 'Overwrite existing files', false)
  .action(async (framework: string, opts: { name: string; port?: number; cwd: string; force?: boolean }) => {
    if (framework !== 'vue' && framework !== 'svelte' && framework !== 'solid') {
      console.error(kleur.red(`unsupported framework: ${framework}. Use vue / svelte / solid.`));
      process.exit(1);
      return;
    }
    const runOpts: ScaffoldFrameworkOptions = {
      cwd: opts.cwd ?? process.cwd(),
      framework: framework as Framework,
      name: opts.name,
    };
    if (opts.port !== undefined) runOpts.port = opts.port;
    if (opts.force !== undefined) runOpts.force = opts.force;
    const r = await scaffoldFrameworkRemote(runOpts);
    console.log(kleur.green(`scaffolded ${r.summary}`));
    for (const f of r.written) console.log(kleur.dim(`  wrote ${path.relative(process.cwd(), path.join(r.appDir, f))}`));
    for (const f of r.skipped) console.log(kleur.yellow(`  skip ${f} (exists; use --force)`));
  });
