import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

async function writeJson(filePath: string, obj: unknown) {
  await fs.outputFile(filePath, JSON.stringify(obj, null, 2) + '\n', 'utf8');
}

async function writeText(filePath: string, content: string) {
  await fs.outputFile(filePath, content, 'utf8');
}

async function ensureEmptyDir(dir: string) {
  const exists = await fs.pathExists(dir);
  if (!exists) return;

  const entries = await fs.readdir(dir);
  // Allow creating into an existing empty directory.
  if (entries.length === 0) return;

  throw new Error(`Target directory is not empty: ${dir}`);
}

export const initCommand = new Command('init')
  .description('Initialize a new MFJS workspace (monorepo)')
  .argument('<name>', 'Folder name for the new workspace')
  .option('-d, --dir <path>', 'Parent directory to create the workspace in', process.cwd())
  .action(async (name: string, opts: { dir: string }) => {
    const workspaceDir = path.resolve(opts.dir, name);

    // eslint-disable-next-line no-console
    console.log(kleur.cyan(`Creating MFJS workspace in ${workspaceDir}`));

    await ensureEmptyDir(workspaceDir);
    await fs.ensureDir(workspaceDir);

    await writeJson(path.join(workspaceDir, 'package.json'), {
      name,
      private: true,
      packageManager: 'pnpm@9.15.5',
      scripts: {
        dev: 'pnpm -r --parallel dev',
        build: 'pnpm -r build',
        test: 'pnpm -r test'
      }
    });

    await fs.outputFile(
      path.join(workspaceDir, 'pnpm-workspace.yaml'),
      'packages:\n  - "packages/*"\n  - "apps/*"\n  - "libs/*"\n\n',
      'utf8'
    );

    await fs.outputFile(
      path.join(workspaceDir, 'README.md'),
      `# ${name}\n\nGenerated by @mfjs/cli.\n`,
      'utf8'
    );

    // Minimal config stub (we’ll grow this into the real config format)
    await writeJson(path.join(workspaceDir, 'mfjs.config.json'), {
      $schema: 'https://mfjs.dev/schemas/mfjs.config.json',
      appsDir: 'apps',
      libsDir: 'libs'
    });

    await writeText(
      path.join(workspaceDir, 'mfjs.config.ts'),
      `export type MfjsConfig = {\n  appsDir: string;\n  libsDir: string;\n  remotes?: Record<string, { url: string }>;\n};\n\nconst config: MfjsConfig = {\n  appsDir: 'apps',\n  libsDir: 'libs'\n};\n\nexport default config;\n`
    );

    // eslint-disable-next-line no-console
  console.log(kleur.green('Done. Next: add apps with `mfjs generate host` (coming next).'));
  });
