/**
 * `jorvel loadtest` — scaffold a k6 load-test script for an SSR/edge target.
 *
 * Drops a `loadtest/<name>.js` file under the workspace with a sensible
 * default profile (ramp-up + steady-state + ramp-down) plus a thresholds
 * block matching JORVEL performance budgets. Targets the host app's URL by
 * default; use `--target` for any URL.
 */

import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

export interface LoadtestScaffoldOptions {
  cwd: string;
  name?: string;
  target?: string;
  vus?: number;
  duration?: string;
  out?: string;
  force?: boolean;
}

export interface LoadtestScaffoldResult {
  path: string;
  written: boolean;
}

export function buildK6Script(opts: {
  target: string;
  vus: number;
  duration: string;
  name: string;
}): string {
  return `// Auto-generated by \`jorvel loadtest\` — k6 load test for ${opts.name}.
// https://k6.io/docs/  — run with: k6 run loadtest/${opts.name}.js
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '30s', target: ${Math.floor(opts.vus / 2)} },   // ramp-up
    { duration: '${opts.duration}', target: ${opts.vus} },   // steady-state
    { duration: '30s', target: 0 },    // ramp-down
  ],
  thresholds: {
    // JORVEL default SSR p95 budget.
    http_req_duration: ['p(95)<400'],
    // <1% non-2xx tolerated.
    http_req_failed: ['rate<0.01'],
    // CDN-cached responses should hit a TTFB SLO under 80ms.
    'http_req_waiting{cached:1}': ['p(95)<80'],
  },
};

const TARGET = __ENV.JORVEL_TARGET || ${JSON.stringify(opts.target)};

export default function () {
  const res = http.get(TARGET, {
    headers: { 'x-jorvel-loadtest': '1' },
    tags: { cached: '0' },
  });
  check(res, {
    'status is 2xx': (r) => r.status >= 200 && r.status < 300,
    'has SSR marker': (r) => typeof r.body === 'string' && r.body.includes('x-jorvel-ssr'),
  });
  sleep(1);
}
`;
}

export async function scaffoldLoadtest(opts: LoadtestScaffoldOptions): Promise<LoadtestScaffoldResult> {
  const cwd = path.resolve(opts.cwd);
  const name = (opts.name ?? 'shell').replace(/[^a-zA-Z0-9_-]/g, '-');
  const dir = opts.out ? path.resolve(cwd, opts.out) : path.join(cwd, 'loadtest');
  await fs.ensureDir(dir);
  const file = path.join(dir, `${name}.js`);
  const exists = await fs.pathExists(file);
  if (exists && !opts.force) {
    return { path: file, written: false };
  }
  const content = buildK6Script({
    target: opts.target ?? 'http://localhost:3000/',
    vus: opts.vus ?? 50,
    duration: opts.duration ?? '2m',
    name,
  });
  await fs.writeFile(file, content, 'utf8');
  return { path: file, written: true };
}

export const loadtestCommand = new Command('loadtest')
  .description('Scaffold a k6 load-test script for an SSR / edge target.')
  .option('--name <name>', 'Test name (becomes the filename). Default: shell')
  .option('--target <url>', 'URL to hit. Default: http://localhost:3000/')
  .option('--vus <n>', 'Peak virtual users for the steady-state stage', (v) => Number(v))
  .option('--duration <d>', 'Steady-state duration (k6 syntax)', '2m')
  .option('--out <dir>', 'Output directory (relative to cwd). Default: loadtest/')
  .option('--cwd <dir>', 'Workspace root', process.cwd())
  .option('--force', 'Overwrite existing file', false)
  .action(async (opts: LoadtestScaffoldOptions) => {
    const runOpts: LoadtestScaffoldOptions = { cwd: opts.cwd ?? process.cwd() };
    if (opts.name !== undefined) runOpts.name = opts.name;
    if (opts.target !== undefined) runOpts.target = opts.target;
    if (opts.vus !== undefined) runOpts.vus = opts.vus;
    if (opts.duration !== undefined) runOpts.duration = opts.duration;
    if (opts.out !== undefined) runOpts.out = opts.out;
    if (opts.force !== undefined) runOpts.force = opts.force;
    const r = await scaffoldLoadtest(runOpts);
    if (!r.written) {
      console.log(kleur.yellow(`skip — ${path.relative(process.cwd(), r.path)} exists (use --force)`));
      return;
    }
    console.log(kleur.green(`wrote ${path.relative(process.cwd(), r.path)}`));
    console.log(kleur.dim(`next:  k6 run ${path.relative(process.cwd(), r.path)}`));
  });
