/**
 * Contract test helpers — generate Vitest cases from a `FederationContract`
 * so a host can verify that every advertised export still resolves on the
 * remote.
 *
 * The helper is framework-neutral: it returns plain async functions, so it
 * also runs under Jest, node:test, or any home-grown harness.
 */

import type { FederationContract } from './federation-contract.js';
import {
  validateFederationContract,
  validateFederationContractKeys,
  type ContractViolation,
} from './federation-contract.js';

export type Container = {
  get: (key: string) => Promise<() => unknown>;
};

export interface ContractCheck {
  name: string;
  run: () => Promise<ContractViolation[]>;
}

export interface ContractSuiteOptions {
  /** Skip the deep container.get checks (run structural checks only). */
  shallow?: boolean;
}

/**
 * Build a list of named checks ready to be plugged into any test runner:
 *
 * ```ts
 * import { describe, it, expect } from 'vitest';
 * import { contractChecks } from '@jorvel/types/testing';
 *
 * describe('dashboard contract', () => {
 *   for (const check of contractChecks(contract, () => loadContainer())) {
 *     it(check.name, async () => {
 *       expect(await check.run()).toEqual([]);
 *     });
 *   }
 * });
 * ```
 */
export function contractChecks(
  contract: FederationContract,
  loadContainer: () => Container | Promise<Container | null | undefined> | null | undefined,
  opts: ContractSuiteOptions = {},
): ContractCheck[] {
  const checks: ContractCheck[] = [];

  checks.push({
    name: 'contract shape is structurally valid',
    run: async () => validateFederationContractKeys(contract, await Promise.resolve(loadContainer() ?? undefined)),
  });

  for (const key of Object.keys(contract.exposes)) {
    checks.push({
      name: `remote "${contract.name}" exposes "${key}"`,
      async run() {
        const container = await Promise.resolve(loadContainer() ?? undefined);
        if (!container) {
          return [{ field: 'container', expected: 'object with .get()', received: 'null' }];
        }
        if (opts.shallow) {
          return validateFederationContractKeys({ ...contract, exposes: { [key]: contract.exposes[key]! } }, container);
        }
        return validateFederationContract(
          { ...contract, exposes: { [key]: contract.exposes[key]! } },
          container,
        );
      },
    });
  }

  return checks;
}

/**
 * Single-shot assertion helper. Throws when the contract is violated.
 * Use inside a single test case when you don't need per-export reporting.
 */
export async function assertContract(
  contract: FederationContract,
  loadContainer: () => Container | Promise<Container | null | undefined> | null | undefined,
  opts: ContractSuiteOptions = {},
): Promise<void> {
  const container = await Promise.resolve(loadContainer() ?? undefined);
  const violations = opts.shallow
    ? validateFederationContractKeys(contract, container ?? null)
    : await validateFederationContract(contract, container ?? null);
  if (violations.length === 0) return;
  const detail = violations.map((v) => `  - ${v.field}: expected ${v.expected}, received ${v.received}`);
  throw new Error(
    `[jorvel/types] Contract "${contract.name}" violated:\n${detail.join('\n')}`,
  );
}

/**
 * Generate a TypeScript source string for a scaffolded vitest contract test.
 * Used by `mfjs generate contract-test` to drop a starting file into a host
 * package. The generated file imports the contract and a loader the user
 * implements (`loadContainer()`).
 */
export interface GenerateOptions {
  /** Import path to the contract file (relative to the generated test). */
  contractImport: string;
  /** Variable name exported by the contract file. */
  contractExport: string;
  /** Optional import for `loadContainer`. */
  loaderImport?: string;
  /** Loader export name. Default: `loadContainer`. */
  loaderExport?: string;
}

export function generateContractTestSource(opts: GenerateOptions): string {
  const loaderImport = opts.loaderImport ?? './load-container.js';
  const loaderExport = opts.loaderExport ?? 'loadContainer';
  return `// Auto-generated by @jorvel/types — \`generateContractTestSource\`.
import { describe, it, expect } from 'vitest';
import { contractChecks } from '@jorvel/types/testing';
import { ${opts.contractExport} } from '${opts.contractImport}';
import { ${loaderExport} } from '${loaderImport}';

describe('${opts.contractExport}', () => {
  for (const check of contractChecks(${opts.contractExport}, ${loaderExport})) {
    it(check.name, async () => {
      const violations = await check.run();
      expect(violations).toEqual([]);
    });
  }
});
`;
}
