import { describe, expect, it } from 'vitest';
import path from 'node:path';
import os from 'node:os';
import fs from 'fs-extra';
import { execa } from 'execa';

async function waitForHttpOk(url: string, timeoutMs: number) {
  const start = Date.now();
  let lastErr: unknown;

  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
      lastErr = new Error(`HTTP ${res.status} ${res.statusText}`);
    } catch (e) {
      lastErr = e;
    }

    await new Promise((r) => setTimeout(r, 250));
  }

  throw new Error(`Timed out waiting for ${url}. Last error: ${lastErr instanceof Error ? lastErr.message : String(lastErr)}`);
}

describe('integration: rspack federation remoteEntry is served', () => {
  it(
    'starts remote dev server and serves /remoteEntry.js when jorvel.federation.json exists',
    async () => {
      if (process.env.JORVEL_SMOKE !== '1') {
        // This test requires spawning a dev server and making HTTP requests.
        // Keep it opt-in to avoid flaky CI/dev environments.
        return;
      }

      const repoRoot = path.resolve(__dirname, '..', '..', '..');
  const tmp = (await fs.mkdtemp(path.join(os.tmpdir(), 'jorvel-it-'))) as string;

      // pnpm needs a workspace root manifest.
      await fs.writeJson(path.join(tmp, 'package.json'), {
        name: 'jorvel-it',
        private: true
      });

      // Make a tiny remote app that uses the same rspack config shape generated by the CLI.
      const remoteDir = path.join(tmp, 'apps', 'dashboard');
      await fs.ensureDir(path.join(remoteDir, 'src'));

      await fs.writeJson(path.join(remoteDir, 'package.json'), {
        name: '@app/dashboard',
        private: true,
        type: 'module',
        scripts: {
          dev: 'rspack serve'
        },
        dependencies: {
          react: '^18.3.1',
          'react-dom': '^18.3.1'
        },
        devDependencies: {
          '@rspack/cli': '^1.5.0',
          '@rspack/core': '^1.5.0',
          '@rspack/dev-server': '^1.1.0',
          typescript: '^5.7.3'
        }
      });

      await fs.writeJson(path.join(remoteDir, 'tsconfig.json'), {
        compilerOptions: {
          target: 'ES2022',
          lib: ['ES2022', 'DOM'],
          module: 'ES2022',
          moduleResolution: 'Bundler',
          strict: true,
          jsx: 'react-jsx',
          skipLibCheck: true
        },
        include: ['src']
      });

      await fs.writeFile(
        path.join(remoteDir, 'index.html'),
        `<!doctype html>\n<html><head><meta charset="UTF-8" /></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n`,
        'utf8'
      );

      await fs.writeFile(
        path.join(remoteDir, 'src/main.tsx'),
        `export {};\n`,
        'utf8'
      );

      await fs.writeFile(
        path.join(remoteDir, 'src/remote.tsx'),
        `export default function RemoteApp(){ return null; }\n`,
        'utf8'
      );

      await fs.writeJson(path.join(remoteDir, 'jorvel.federation.json'), {
        name: 'dashboard',
        filename: 'remoteEntry.js',
        exposes: {
          './App': './src/remote.tsx'
        },
        shared: {}
      });

      await fs.writeFile(
        path.join(remoteDir, 'rspack.config.mjs'),
        `import { rspack } from '@rspack/core';\nimport path from 'node:path';\nimport fs from 'node:fs';\n\nconst federationPath = path.join(process.cwd(), 'jorvel.federation.json');\nconst federation = fs.existsSync(federationPath)\n  ? JSON.parse(fs.readFileSync(federationPath, 'utf8'))\n  : null;\n\nexport default {\n  mode: 'development',\n  entry: './src/main.tsx',\n  devServer: { port: 4101, historyApiFallback: true },\n  output: { uniqueName: 'dashboard', publicPath: 'auto' },\n  resolve: { extensions: ['.tsx', '.ts', '.js'] },\n  module: {\n    rules: [\n      {\n        test: /\\.(ts|tsx)$/,\n        exclude: /node_modules/,\n        loader: 'builtin:swc-loader',\n        options: {\n          jsc: {\n            parser: { syntax: 'typescript', tsx: true },\n            transform: { react: { runtime: 'automatic' } }\n          }\n        }\n      }\n    ]\n  },\n  plugins: [\n    new rspack.HtmlRspackPlugin({ template: './index.html' }),\n    ...(federation\n      ? [\n          new rspack.container.ModuleFederationPlugin({\n            name: federation.name,\n            filename: federation.filename,\n            exposes: federation.exposes,\n            remotes: federation.remotes,\n            shared: federation.shared\n          })\n        ]\n      : [])\n  ]\n};\n`,
        'utf8'
      );

      // Install deps at the real repo root (so we can reuse workspace resolution + the pnpm store).
      // Then point the temp app at the local @jorvel/event-bus package via a file: dependency.
      await execa('pnpm', ['install'], {
        cwd: repoRoot,
        env: process.env,
        stdio: 'inherit'
      });

      // Install deps for the temp project (so rspack is available).
      await execa('pnpm', ['install'], {
        cwd: tmp,
        env: process.env,
        stdio: 'inherit'
      });

      // Start rspack dev-server.
      const child = execa('pnpm', ['dev'], {
        cwd: remoteDir,
        env: { ...process.env, BROWSER: 'none' },
        stdio: 'inherit'
      });

      try {
        await waitForHttpOk('http://localhost:4101/remoteEntry.js', 45_000);
        const res = await fetch('http://localhost:4101/remoteEntry.js');
        const body = await res.text();

        expect(res.ok).toBe(true);
        // Basic sanity: the response should look like JS, not HTML.
        expect(body).toContain('dashboard');
      } finally {
  child.kill('SIGTERM');
      }

      // Ensure we don't leave behind huge temp dirs.
      await fs.remove(tmp);

      // Keep lint happy: avoid unused repoRoot (it documents intent).
      expect(repoRoot.length).toBeGreaterThan(1);
    },
    180_000
  );
});
