import { describe, expect, it } from 'vitest';
import os from 'node:os';
import path from 'node:path';
import fs from 'fs-extra';

import { routesCommand } from '../src/commands/routes.js';
import { generateCommand } from '../src/commands/generate.js';

async function runGenerate(argv: string[], cwd: string) {
  generateCommand.exitOverride();
  const prev = process.cwd();
  process.chdir(cwd);
  try {
    await generateCommand.parseAsync(argv, { from: 'user' });
  } finally {
    process.chdir(prev);
  }
}

async function runRoutes(cwd: string) {
  routesCommand.exitOverride();
  const prev = process.cwd();
  process.chdir(cwd);
  try {
    await routesCommand.parseAsync(['--dir', cwd], { from: 'user' });
  } finally {
    process.chdir(prev);
  }
}

describe('mfjs routes', () => {
  it('writes host + remote manifests and generates remote src/mfjs.routes.ts module from src/pages', async () => {
  const tmp = (await fs.mkdtemp(path.join(os.tmpdir(), 'mfjs-routes-'))) as string;

    await runGenerate(['host', 'shell', '--dir', tmp, '--port', '3000'], tmp);
    await runGenerate(['remote', 'dashboard', '--dir', tmp, '--port', '3001'], tmp);

    // Create remote pages
    const remotePages = path.join(tmp, 'apps', 'dashboard', 'src', 'pages');
    await fs.ensureDir(remotePages);
    await fs.outputFile(path.join(remotePages, 'index.tsx'), 'export default function Index() { return null; }\n');
    await fs.ensureDir(path.join(remotePages, 'reports'));
    await fs.outputFile(
      path.join(remotePages, 'reports', '[id].tsx'),
      'export default function Report() { return null; }\n'
    );

    await runRoutes(tmp);

    // Per-app manifest
    expect(await fs.pathExists(path.join(tmp, 'apps', 'dashboard', 'mfjs.routes.json'))).toBe(true);

    // Generated routes module for remote
    const routesModulePath = path.join(tmp, 'apps', 'dashboard', 'src', 'mfjs.routes.ts');
    const routesModule = await fs.readFile(routesModulePath, 'utf8');
    expect(routesModule).toContain("AUTO-GENERATED by `mfjs routes`");
    expect(routesModule).toContain("import type { RemotePageRoute } from '@mfjs/runtime'");
  expect(routesModule).toContain('path: "/"');
  expect(routesModule).toContain('path: "/reports/:id"');
  expect(routesModule).toContain('import("./pages/index.tsx")');

    // Host route mount table
    const hostRoutesPath = path.join(tmp, 'apps', 'shell', 'mfjs.routes.host.json');
    const hostRoutes = await fs.readJson(hostRoutesPath);
    expect(hostRoutes.routes).toEqual([
  { path: '/', remote: 'dashboard', module: './App' },
  { path: '/dashboard/*', remote: 'dashboard', module: './App' },
    ]);
  });
});
