// THIS FILE IS AUTO-GENERATED by `jorvel routes`.
// It exposes the remote's file-based route table for the host to consume.
import type { RemotePageRoute } from '@jorvel/runtime';

export const pages: RemotePageRoute[] = [
  { path: "/users/:id", load: () => import("./pages/users/[id].tsx") },
  { path: "/settings", load: () => import("./pages/settings.tsx") },
  { path: "/", load: () => import("./pages/index.tsx") },
];

export default pages;
