import React from 'react';
import ReactDOM from 'react-dom/client';
import { createRouter, resolveRemotePage } from '@mfjs/runtime';
import pages from './mfjs.routes';

function App() {
  const router = React.useMemo(() => createRouter(), []);
  const [path, setPath] = React.useState(() => {
    // Prefer the actual location on first load (deep links like /reports/1).
    return `${window.location.pathname}${window.location.search}${window.location.hash}` || router.getPath();
  });
  const [Remote, setRemote] = React.useState<React.ComponentType | null>(null);

  React.useEffect(() => router.subscribe(setPath), [router]);

  React.useEffect(() => {
    let mounted = true;
    const run = async () => {
      // Always resolve using the current pathname (ignore query/hash).
      const current = (path || '/').split('?')[0].split('#')[0] || '/';
      const res = await resolveRemotePage(pages, current);
      if (!mounted) return;
      setRemote(() => (res?.Component as any) ?? null);
    };
    void run();
    return () => {
      mounted = false;
    };
  }, [path]);

  return (
    <div style={{ fontFamily: 'system-ui', padding: 16 }}>
      <h1>dashboard</h1>
      <p>Generated by @mfjs/cli</p>
      <p style={{ opacity: 0.7 }}>
        Current path: <code>{path}</code>
      </p>

      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}>
        <button onClick={() => router.navigate({ to: '/' })}>/</button>
        <button onClick={() => router.navigate({ to: '/reports/1' })}>/reports/1</button>
      </div>

      {Remote ? <Remote /> : <p>No route matched.</p>}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
